### ISSUE TITLE
HHVM on Fedora 24/25

### ISSUE THREAD

**Issue by hworld** [ulyaoth/repository#1089]
Hey there, I came across your repo while trying to find options for getting HHVM on fedora. It seems that it is only available for Fedora 23 and lower? Is there any possibility to get it for newer fedora versions? 

Looking at this page it lists up to Fedora 25.
https://www.ulyaoth.net/resources/ulyaoth-repository.6/

Is it that HHVM's dependencies don't work on F24/25?

**Comment by sbagmeijer** [comment]
hi @hworld the build somehow does not work on those two operating systems I expect the GCC version is to high or some component won't build correctly.

If you have any information on how to build it on those two operating system I would gladly hear it, i actually use hhvm also and still on F23 at the moment because of it.

**Comment by hworld** [comment]
Aw, bummer. I was actually looking for a repo like this because the build didn't work on F24 for me. haha

Mine seemed to stop randomly right after the mysql module thing. It didn't really give any errors, and I didn't feel like spending a few days trying to figure it out.

If I ever figure it out, though, I'll be sure to post it here. Thanks for the response!
